In [1]:
import numpy as np
import os

In [2]:
file_location = os.path.join('data', 'water.xyz')
print(file_location)

data/water.xyz


In [3]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

In [4]:
xyz_file = np.genfromtxt(fname=file_location, dtype= 'unicode', skip_header=2)

In [5]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [6]:
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:].astype(float)

In [7]:
print(coordinates)
print(symbols)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
['O' 'H1' 'H2']


In [8]:
num_atoms = len(symbols)
for i in range(0, num_atoms):
    for j in range(0, num_atoms):
        x_distance = coordinates[i,0] - coordinates[j,0]
        y_distance = coordinates[i,1] - coordinates[j,1]
        z_distance = coordinates[i,2] - coordinates[j,2]
        distance = np.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
        print(F'{symbols[i]} to {symbols[j]} : {distance:.3f}')
        

O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000


In [ ]:
# I am going to modify my code to only print the atoms that are bonded
# my arbitrary rule is going to be that the distance must be less than 1.5
# to be considered a bond



In [12]:
num_atoms = len(symbols)
for i in range(0, num_atoms):
    for j in range(0, num_atoms-2):
        x_distance = coordinates[i,0] - coordinates[j,0]
        y_distance = coordinates[i,1] - coordinates[j,1]
        z_distance = coordinates[i,2] - coordinates[j,2]
        distance = np.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
        if distance > 0 and distance < 1.5:
            print(F'{symbols[i]} to {symbols[j]} : {distance:.3f}')

H1 to O : 0.969
H2 to O : 0.969


In [13]:
num_atoms = len(symbols)
for i in range(0, num_atoms):
    for j in range(i+1, num_atoms):
        x_distance = coordinates[i,0] - coordinates[j,0]
        y_distance = coordinates[i,1] - coordinates[j,1]
        z_distance = coordinates[i,2] - coordinates[j,2]
        distance = np.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
        if distance > 0 and distance < 1.5:
            print(F'{symbols[i]} to {symbols[j]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [14]:
num_atoms = len(symbols)
for i in range(0, num_atoms):
    for j in range(0, num_atoms):
        if i<j:
            x_distance = coordinates[i,0] - coordinates[j,0]
            y_distance = coordinates[i,1] - coordinates[j,1]
            z_distance = coordinates[i,2] - coordinates[j,2]
            distance = np.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
            if distance > 0 and distance < 1.5:
                print(F'{symbols[i]} to {symbols[j]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [15]:
def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = np.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
    return distance
    

In [19]:
calculate_distance([0,0,0], [1,1,1])

1.7320508075688772

In [22]:
# assert statements will return True or False with an error
assert np.isclose(calculate_distance([0,0,0], [1,1,1]),  np.sqrt(3), 1e-8)

In [43]:
# modify the bond_check function 
# to accept a minimum length and a maximum length as inputs
def bond_check(bond_length, min_length=0., max_length=1.5):
    """
    Checks a bond distance to see if it meets the criteria for a bond based on a minimum and maximum length.  
    The default minimum is 0 angstroms.  The default maximum is 1.5 angstroms.
    """
    if bond_length > min_length and bond_length < max_length:
        return True
    else:
        return False
    


In [44]:
bond_check(1.2, 1.0, 1.5)

True

In [45]:
help(bond_check)

Help on function bond_check in module __main__:

bond_check(bond_length, min_length=0.0, max_length=1.5)
    Checks a bond distance to see if it meets the criteria for a bond based on a minimum and maximum length.  
    The default minimum is 0 angstroms.  The default maximum is 1.5 angstroms.

